version: '3.5'

services:
    db:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=user

    frontend:
      image: frontend-example-docker
      ports:
        - 5000:5000
      environment:
        - API_URL=http://localhost:8000

    backend:
      image: backend-example-docker
      ports:
        - 8000:8000
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - DB_USERNAME=user
        - DB_PASSWORD=password
        - DB_HOST=db
      depends_on:
        - db

    redis:
      image: redis
