version: '3.5'

services:
    nginx:
      image: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - frontend
        - backend

    db:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=user
      volumes:
        - ./db:/var/lib/postgresql/data

    frontend:
      image: frontend-example-docker-node
      environment:
        - API_URL=http://localhost/api

    backend:
      image: backend-example-docker-node
      environment:
        - REDIS=redis
        - DB_USERNAME=user
        - DB_PASSWORD=password
        - DB_HOST=db
      depends_on:
        - db

    redis:
      image: redis
      volumes:
        - ./cache:/data
